steps:
    # Download .env file
    - name: "gcr.io/cloud-builders/gsutil"
      args: ["cp", "gs://env-variables-umami/.prod.env", ".env"]
    # build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/umami', '.' ]
    # push the container image to gcr
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'push', 'gcr.io/${_PROJECT_ID}/umami']
      # Deploy container image to Cloud Run
    - name: "gcr.io/cloud-builders/gcloud"
      args: ['run', 'deploy', 'umami', '--image', 'gcr.io/${_PROJECT_ID}/umami', '--region', 'us-central1', '--platform', 'managed', '--min-instances', '1', '--allow-unauthenticated', '--add-cloudsql-instances', '${_CLOUDSQL_CONNECTION_NAME}']
